name: Run Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Обновляем Node.js до версии 18

    - name: Install npm 9
      run: |
        npm install -g npm@9  # Обновляем npm до версии 9

    - name: Install dependencies
      run: |
        npm ci  # Устанавливаем зависимости, включая Playwright

    - name: Install Playwright Browsers
      run: npx playwright install  # Устанавливаем браузеры для Playwright

    - name: Install Playwright dependencies
      run: npx playwright install-deps  # Устанавливаем необходимые зависимости для Playwright

    - name: Install missing system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2 \
          libicu63 \
          libffi-dev \
          libvpx-dev \
          x264 \
          libvpx \
          libgtk-3-0 \
          libx11-xcb1 \
          libsecret-1-0 \
          libnss3 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libcups2 \
          libdbus-glib-1-2 \
          libflite1 \
          libgdk-pixbuf2.0-0 \
          libdbus-1-3 \
          libxrender1 \
          libglib2.0-0 \
          libudev1 \
          libv4l-0 \
          libopus0 \
          libgcrypt20 \
          libfontconfig1 \
          libxt6 \
          libnspr4 \
          libevent-2.1-6 \
          libx264-160 \
          libgbm1 \
          libnss3-tools  # Устанавливаем дополнительные зависимости

    - name: Install Allure Commandline
      run: |
        sudo apt-get install -y allure  # Устанавливаем Allure на Ubuntu

    - name: Run Playwright Tests with Allure
      run: |
        npx playwright test --reporter=allure-playwright  # Запуск тестов с Allure репортером

    - name: Generate Allure Report
      run: |
        allure generate --clean  # Генерация Allure отчета

    - name: Upload Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: allure-report  # Указываем папку, в которой находится отчет
        target_branch: gh-pages  # Загружаем на ветку gh-pages
        commit_message: "Deploy Allure Report"
        user_name: "github-actions"
        user_email: "github-actions@github.com"
