name: Playwright Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Используйте вашу версию Node.js

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright Tests
      run: |
        npx playwright test --reporter=line,allure-playwright # Убедитесь, что Allure интеграция настроена.

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
